<%@ Page Title="" Language="C#" MasterPageFile="~/MainMasterPage.master" AutoEventWireup="true" CodeFile="AboutUs.aspx.cs" Inherits="AboutUs" %>

<asp:Content ID="Content1" ContentPlaceHolderID="ContentPlaceHolder1" Runat="Server">
    <h1 align="left" style="margin: 0px 0px 0.75em; padding: 0px; border: 0px; outline: 0px; font-weight: bold; font-style: normal; font-size: 1.5em; font-family: Arial, &quot;Century Gothic&quot;, sans-serif; vertical-align: baseline; line-height: 1.1em; color: rgb(200, 31, 37); font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255);">About UCM</h1>
    <p style="margin: 0px 0px 1.3em; padding: 0px; border: 0px; outline: 0px; font-weight: normal; font-style: normal; font-size: 0.75em; font-family: Arial, Helvetica, Verdana, sans-serif; vertical-align: baseline; color: rgb(0, 0, 0); font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255);">
        <strong style="margin: 0px; padding: 0px; border: 0px; outline: 0px; font-weight: bold; font-style: inherit; font-size: 12px; font-family: inherit; vertical-align: baseline;">About the University of Central Missouri</strong><br />
        The University of Central Missouri experience transforms students into lifelong learners, dedicated to service, with the knowledge, skills and confidence to succeed and lead in the region, state, nation and world.</p>
    <p align="right" style="margin: 0px 0px 1.3em; padding: 0px; border: 0px; outline: 0px; font-weight: normal; font-style: normal; font-size: 0.75em; font-family: Arial, Helvetica, Verdana, sans-serif; vertical-align: baseline; color: rgb(0, 0, 0); font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255);">
        <img align="right" alt="UCM quad" height="212" hspace="5" src="https://www.ucmo.edu/about/images/quad_000.jpg" style="border: 0px; outline: 0px; font-weight: inherit; font-style: inherit; font-size: 12px; font-family: inherit;" vspace="5" width="325" /></p>
    <p style="margin: 0px 0px 1.3em; padding: 0px; border: 0px; outline: 0px; font-weight: normal; font-style: normal; font-size: 0.75em; font-family: Arial, Helvetica, Verdana, sans-serif; vertical-align: baseline; color: rgb(0, 0, 0); font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255);">
        <strong style="margin: 0px; padding: 0px; border: 0px; outline: 0px; font-weight: bold; font-style: inherit; font-size: 12px; font-family: inherit; vertical-align: baseline;">Reasons to Believe in a UCM education.</strong></p>
    <ul style="margin: 0px 0px 1.5em; padding: 0px 0px 0px 24px; border: 0px; outline: 0px; font-weight: normal; font-style: normal; font-size: 16px; font-family: Arial, Helvetica, Verdana, sans-serif; vertical-align: baseline; list-style: disc; position: relative; color: rgb(0, 0, 0); font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255);">
        <li style="margin: 0px; padding: 0px; border: 0px; outline: 0px; font-weight: inherit; font-style: inherit; font-size: 12px; font-family: inherit; vertical-align: baseline; position: relative;"><strong style="margin: 0px; padding: 0px; border: 0px; outline: 0px; font-weight: bold; font-style: inherit; font-size: 12px; font-family: inherit; vertical-align: baseline;">A Culture of service</strong><span class="Apple-converted-space">&nbsp;</span>connects students to something bigger than themselves through opportunities to give back to the community such as Habitat for Humanity.</li>
        <li style="margin: 0px; padding: 0px; border: 0px; outline: 0px; font-weight: inherit; font-style: inherit; font-size: 12px; font-family: inherit; vertical-align: baseline; position: relative;"><strong style="margin: 0px; padding: 0px; border: 0px; outline: 0px; font-weight: bold; font-style: inherit; font-size: 12px; font-family: inherit; vertical-align: baseline;">Engaged Learning<span class="Apple-converted-space">&nbsp;</span></strong>through hands-on learning experiences in and outside the classroom includes programs such as Innovative Public Relations and the Integrative Business Experience.</li>
        <li style="margin: 0px; padding: 0px; border: 0px; outline: 0px; font-weight: inherit; font-style: inherit; font-size: 12px; font-family: inherit; vertical-align: baseline; position: relative;"><strong style="margin: 0px; padding: 0px; border: 0px; outline: 0px; font-weight: bold; font-style: inherit; font-size: 12px; font-family: inherit; vertical-align: baseline;">Future-Focused Academics</strong><span class="Apple-converted-space">&nbsp;</span>offers state-of-the-art equipment such as Redbird simulators and internships to equip students with up-to-date skills.</li>
        <li style="margin: 0px; padding: 0px; border: 0px; outline: 0px; font-weight: inherit; font-style: inherit; font-size: 12px; font-family: inherit; vertical-align: baseline; position: relative;"><strong style="margin: 0px; padding: 0px; border: 0px; outline: 0px; font-weight: bold; font-style: inherit; font-size: 12px; font-family: inherit; vertical-align: baseline;">A Worldly Perspective</strong><span class="Apple-converted-space">&nbsp;</span>enhances students’ college experience by offering opportunities to participate in study abroad programs in countries such as France or New Zealand.</li>
    </ul>
    <p style="margin: 0px 0px 1.3em; padding: 0px; border: 0px; outline: 0px; font-weight: normal; font-style: normal; font-size: 0.75em; font-family: Arial, Helvetica, Verdana, sans-serif; vertical-align: baseline; color: rgb(0, 0, 0); font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255);">
        <strong style="margin: 0px; padding: 0px; border: 0px; outline: 0px; font-weight: bold; font-style: inherit; font-size: 12px; font-family: inherit; vertical-align: baseline;">Champions of Student Success<br />
        </strong>UCM’s<span class="Apple-converted-space">&nbsp;</span><a href="http://www.ucmo.edu/contract" style="margin: 0px; padding: 0px; border: 0px; outline: 0px; font-weight: inherit; font-style: inherit; font-size: 12px; font-family: inherit; vertical-align: baseline; color: rgb(200, 31, 37); text-decoration: none;">Learning to a Greater Degree Contract</a><span class="Apple-converted-space">&nbsp;</span>is our promise to you that with your commitment, we&#39;ll help you complete a more valuable degree on time. We foster a community of engagement by providing you with resources to help you succeed, such as our Student Success Center and Writing Center. We are proud of our more than 90 percent employment rate for students six months after graduation.</p>
    <p style="margin: 0px 0px 1.3em; padding: 0px; border: 0px; outline: 0px; font-weight: normal; font-style: normal; font-size: 0.75em; font-family: Arial, Helvetica, Verdana, sans-serif; vertical-align: baseline; color: rgb(0, 0, 0); font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255);">
        <strong style="margin: 0px; padding: 0px; border: 0px; outline: 0px; font-weight: bold; font-style: inherit; font-size: 12px; font-family: inherit; vertical-align: baseline;">Focused on the Future<br />
        </strong>Founded in 1871 in Warrensburg, Missouri with only a few dozen students, more than 140 years later, UCM has grown to serve more than 14,000 students. Our diverse student population represents nearly every state and 50 countries across the globe.</p>
    <p style="margin: 0px 0px 1.3em; padding: 0px; border: 0px; outline: 0px; font-weight: normal; font-style: normal; font-size: 0.75em; font-family: Arial, Helvetica, Verdana, sans-serif; vertical-align: baseline; color: rgb(0, 0, 0); font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255);">
        Questions?<span class="Apple-converted-space">&nbsp;</span><a href="http://www.ucmo.edu/contact/" style="margin: 0px; padding: 0px; border: 0px; outline: 0px; font-weight: inherit; font-style: inherit; font-size: 12px; font-family: inherit; vertical-align: baseline; color: rgb(200, 31, 37); text-decoration: none;">Let us answer them</a>. Better yet, why not come for a<span class="Apple-converted-space">&nbsp;</span><a href="http://www.ucmo.edu/undergrad/visit/" style="margin: 0px; padding: 0px; border: 0px; outline: 0px; font-weight: inherit; font-style: inherit; font-size: 12px; font-family: inherit; vertical-align: baseline; color: rgb(200, 31, 37); text-decoration: none;">visit</a><span class="Apple-converted-space">&nbsp;</span>and tour campus?</p>
</asp:Content>

